### ISSUE TITLE
CLI does not work

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/eynollah#11]
I cannot get `eynollah` to run. Here's what I did for installation:

    git clone https://github.com/qurator-spk/eynollah
    pip install -e eynollah
    make -C eynollah models

Everything went smoothly. Now I wanted to run on my image:

    mkdir LINES-EYNOLLAH
    eynollah -i ORIGINAL/FILE_0002_ORIGINAL.jpg -o LINES-EYNOLLAH -m /data/ocr-d/eynollah/models_eynollah -fl -ae -cl

This returns after about 1sec without doing anything (exit value is 1). It's the same if I remove `-fl -ae -cl`. (In fact, it's still the same if I remove the entire `-m` option.) No error, no result.

**Comment by cneud** [comment]
I am not 100% sure but I think the option flags are mutually eyclusive - what happens with 
`eynollah -i ORIGINAL/FILE_0002_ORIGINAL.jpg -o LINES-EYNOLLAH -m /data/ocr-d/eynollah/models_eynollah -fl`?

**Comment by kba** [comment]
A fresh install from master fails for me at the moment. @bertsky I will work on the XML handling and OCR-D interface and will get back to you once this is in a working state again.

**Comment by bertsky** [comment]
> I am not 100% sure but I think the option flags are mutually eyclusive - what happens with
> `eynollah -i ORIGINAL/FILE_0002_ORIGINAL.jpg -o LINES-EYNOLLAH -m /data/ocr-d/eynollah/models_eynollah -fl`?
> 
> Edit:
> Sorry I think it should be
> `eynollah -i ORIGINAL/FILE_0002_ORIGINAL.jpg -o LINES-EYNOLLAH -m /data/ocr-d/eynollah/models_eynollah -fl=true`

It's `-fl`, not `-fl=true` (I was confused by this myself from the README, but a look into cli.py confirms this is just a `@click.option` with `is_flag=True`).

As I said, it does not even work without any flags or without `-m`.

**Comment by cneud** [comment]
Ouch but thanks @kba! 

@bertsky I checked again and I am still on https://github.com/qurator-spk/eynollah/commit/3d808067fe80b1a84a54c333fa84a675126f66e6 which works fine for me with the flags set as above.

**Comment by bertsky** [comment]
> I checked again and I am still on [3d80806](https://github.com/qurator-spk/eynollah/commit/3d808067fe80b1a84a54c333fa84a675126f66e6) which works fine for me with the flags set as above.

@cneud I checked out 3d80806, re-installed (`pip install -e .`) and tried again:

```
Traceback (most recent call last):
  File "/data/ocr-d/ocrd_all/venv/bin/eynollah", line 33, in <module>
    sys.exit(load_entry_point('eynollah', 'console_scripts', 'eynollah')())
  File "/data/ocr-d/ocrd_all/venv/bin/eynollah", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/ocr-d/eynollah/sbb_newspapers_org_image/cli.py", line 2, in <module>
    from sbb_newspapers_org_image.eynollah import eynollah
  File "/data/ocr-d/eynollah/sbb_newspapers_org_image/eynollah.py", line 68, in <module>
    from .utils.separate_lines import (
  File "/data/ocr-d/eynollah/sbb_newspapers_org_image/utils/separate_lines.py", line 15, in <module>
    from .utils import (
ModuleNotFoundError: No module named 'sbb_newspapers_org_image.utils.utils'
```

And then if I fix this one buggy import (replacing `.utils` with `.`), I get:
```
Traceback (most recent call last):
  File "/data/ocr-d/ocrd_all/venv/bin/eynollah", line 33, in <module>
    sys.exit(load_entry_point('eynollah', 'console_scripts', 'eynollah')())
  File "/data/ocr-d/ocrd_all/venv/bin/eynollah", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/ocr-d/ocrd_all/venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/ocr-d/eynollah/sbb_newspapers_org_image/cli.py", line 2, in <module>
    from sbb_newspapers_org_image.eynollah import eynollah
  File "/data/ocr-d/eynollah/sbb_newspapers_org_image/eynollah.py", line 116, in <module>
    from utils.xml import create_page_xml
ModuleNotFoundError: No module named 'utils'
```

Here `utils` needs to be replaced with `.utils` – and then it runs!

**Comment by kba** [comment]
Thanks for tracking the problem down, I'll fix it right away.r
