### ISSUE TITLE
Support for ROCm and more recent tensorflow versions

### ISSUE THREAD

**Issue by Emersont1** [qurator-spk/eynollah#143]
Currently the tool does not support use of more recent tensorflow libraries (is possibly reliant on `ensorflow.compat.v1.keras.backend`)

Adding support for more recent versions of tensorflow will allow running on AMD based systems via the tensorflow-rocm package on a system with an up-to-date install of ROCm (6.2)

When I try using tensorflow-rocm 2.18, I get no output, but running with tensorflow 2.18, I get the following
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734536993.371913  205530 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734536993.373741  205530 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/home/et1/Code/eynollah/venv/bin/eynollah", line 5, in <module>
    from eynollah.cli import main
  File "/home/et1/Code/eynollah/venv/lib64/python3.11/site-packages/eynollah/cli.py", line 4, in <module>
    from eynollah.eynollah import Eynollah
  File "/home/et1/Code/eynollah/venv/lib64/python3.11/site-packages/eynollah/eynollah.py", line 33, in <module>
    from tensorflow.compat.v1.keras.backend import set_session
ModuleNotFoundError: No module named 'tensorflow.compat.v1.keras'
```

**Comment by cneud** [comment]
Dear @Emersont1 thank you for you interest in this software. We are (painfully) aware of the limitation but since TF 2.16 changes from Keras API v2 to v3 it requires some effort to support newer TF versions. We are on the way of training new models and refactoring the codebase accordingly but due to vacation of the main developer, it will likely take until February/March before a new release will be ready.
