### ISSUE TITLE
AttributeError: 'EynollahProcessor' object has no attribute 'resolve_resource'

### ISSUE THREAD

**Issue by neingeist** [qurator-spk/eynollah#35]
~~~
% ocrd-eynollah-segment -I OCR-D-IMG -O OCR-D-SEG-LINE -P models /var/lib/eynollah
17:49:26.462 INFO eynollah - INPUT FILE PHYS_0024 (1/1) 
Traceback (most recent call last):
  File "/usr/local/bin/ocrd-eynollah-segment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/qurator/eynollah/ocrd_cli.py", line 8, in main
    return ocrd_cli_wrap_processor(EynollahProcessor, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ocrd/decorators/__init__.py", line 81, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ocrd/processor/helpers.py", line 70, in run_processor
    processor.process()
  File "/usr/local/lib/python3.6/dist-packages/qurator/eynollah/processor.py", line 46, in process
    'dir_models': self.resolve_resource(self.parameter['models']),
AttributeError: 'EynollahProcessor' object has no attribute 'resolve_resource'
~~~

I am investigating if my core version is old, and report back here

**Comment by neingeist** [comment]
My hunch was correct: I had an old core installed. I'll be submitting a PR.

**Comment by neingeist** [comment]
Submitted from my private account, accidently. I'm closing and reopening it from my "business" account (which I strongly prefer for this.)
