### ISSUE TITLE
Cannot run the file giving error. 

### ISSUE THREAD

**Issue by rajsaraiya009** [qurator-spk/eynollah#56]
Traceback (most recent call last):
  File "/usr/bin/pytest", line 11, in <module>
    load_entry_point('pytest==3.3.2', 'console_scripts', 'pytest')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python2.7/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python2.7/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'

After running pytest tests it givens me this kind of error. Can anyone help me out with this ?

**Comment by kba** [comment]
`/usr/local/lib/python2.7`

Can you try again with an up-to-date version of Python (i.e. `> 3.5`)?

**Comment by cneud** [comment]
Hi @rajsaraiya009, unfortunately we do not support Python 2.7 but only 3.5-3.7 (3.8 and newer do not have no support for tensorflow-1.15.x which is required here).

I am closing this, but feel free to re-open or file a new issue in case problems persist with other Python versions.
