### ISSUE TITLE
Cant run eynollah

### ISSUE THREAD

**Issue by IKetchup** [qurator-spk/eynollah#59]
I just installed eynollah and I want to rty it on a jpg image.

I type in my cli the following ```eynollah -i repport_6.jpg -o eynollah```

But the following error keep coming regardless of my output foler

```Traceback (most recent call last):
  File "D:\Anaconda\envs\eynollah\Scripts\eynollah-script.py", line 33, in <module>
    sys.exit(load_entry_point('eynollah', 'console_scripts', 'eynollah')())
  File "D:\Anaconda\envs\eynollah\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\eynollah\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\eynollah\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\eynollah\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\eynollah\qurator\eynollah\cli.py", line 148, in main
    headers_off=headers_off,
  File "C:\Users\\eynollah\qurator\eynollah\eynollah.py", line 137, in __init__
    self.model_dir_of_enhancement = dir_models + "/model_enhancement.h5"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Im on windows10 working on a conda environement

Does someone know where the issue come from and how to fix it?

**Comment by vahidrezanezhad** [comment]
dear @IKetchup , you are missing the models. provide the directory of models with -m option. Then it should work :)

**Comment by mikegerber** [comment]
Just to clarify a bit: If there was a `required=True`, the above call to the CLI would have given a useful error message, that the `--model` option is required to run eynollah.

**Comment by cneud** [comment]
> The model's @click.option is missing a required=True

Well spotted, can you confirm and amend this @vahidrezanezhad ?
